site_name: Flank
theme:
  name: material
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: "index.md"
  - Why Flank:
      - Initial motivations: "motivations.md"
      - Existing tools didn't solve our problem: "existing.md"
      - Goals and Core Concepts: "goals.md"
  - Comparisons:
      - "Flowchart of Comparisons": "comparisons/master-flowchart.md"
      - Retool: "comparisons/retool.md"
      - Postman: "comparisons/postman.md"
      - Swagger UI / OpenAPI: "comparisons/swagger.md"
      - Zapier: "comparisons/zapier.md"
      - "Tableau, Power BI, Looker": "comparisons/bi.md"
      - "Streamlit": "comparisons/streamlit.md"
      - "PopSQL": "comparisons/popsql.md"
      - "Metabase": "comparisons/metabase.md"
      - "React, etc": "comparisons/custom.md"
  - Quick Start: 
    - FastAPI + Jupyter: "quickstarts/jupyter-fastapi.md"
  - Use Cases:
      - "Turn a data request into a permament tool": "use-cases/one-off.md"
  - Integrations:
      - SQL Server: "integrations/mssql.md"
      - REST APIs: "integrations/rest.md"
      - AWS Lambda: "integrations/lambda.md"
      - Azure Function Apps: "integrations/az-functions.md"
  - More:
      - Features and Benefits: "features.md"
      - Design Decisions and Tradeoffs: "tradeoffs.md"
      - Miscellaneous: "miscellaneous.md"
