site_name: Flank
theme:
  name: material
  logo: 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: "assets/flank-logo.jpeg"   
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

nav:
  - Home: "index.md"
  # - Quick Start: "quickstarts/jupyter-fastapi.md"
  - How Does It Work?: "how-does-it-work.md"
  - Use Cases: "use-cases.md"
  - Comparisons: "comparisons/all-comparisons.md"
  - Technical Details: "integrations/all-integrations.md"
  - Contact Us: "contact.md"
