site_name: Flank
theme:
  name: material
  logo: 
  palette:
    primary: deep purple
  favicon: "assets/flank-logo.jpeg"   
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

nav:
  - Home: "index.md"
  - Background: "background.md"
  - Comparisons: "comparisons/all-comparisons.md"
  - Quick Start: "quickstarts/jupyter-fastapi.md"
  - Integrations: "integrations/all-integrations.md"
  - More:
      - Design Decisions and Tradeoffs: "tradeoffs.md"
      - Miscellaneous: "miscellaneous.md"
