site_name: Flank
theme:
  name: material
  logo: 
  palette:
    primary: deep purple
  favicon: "assets/flank-logo.jpeg"   
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: "index.md"
  - Background: "background.md"
  - Comparisons: "comparisons/all-comparisons.md"
  - Quick Start: "quickstarts/jupyter-fastapi.md"
  - Integrations:
      - SQL Server: "integrations/mssql.md"
      - REST APIs: "integrations/rest.md"
      - AWS Lambda: "integrations/lambda.md"
      - Azure Function Apps: "integrations/az-functions.md"
  - More:
      - Features and Benefits: "features.md"
      - Design Decisions and Tradeoffs: "tradeoffs.md"
      - Miscellaneous: "miscellaneous.md"
